defaults:
  - _self_
  - data: data
  - model: model
  # # Only change Overrides (only one override per group (data/model/...) allowed)
  # # Command line override would look like: python train.py data=splitXY model=modelZ
  - override /data: treeAI_vernon
  - override /model: model_treeAI
  - override hydra/launcher: submitit_slurm

# # select exp_name and ckpt_type (best/last) for which test metrics are to be calculated
exp_name: 20251119_093300.602560_Unet_resnet50_CE_320_62_wrs_True #20251026_190008.509178_Unet_resnet50_HierarchicalCE_320_62_wrs_True
ckpt_type: best
log_name: 'treeAI'
d_matrix_eval: 'distancematrix/taxonomy_distance_matrix.pt' #"/home/c/shursc/code/tree_identification/distancematrix/taxonomy_distance_matrix.pt"

# # Reproducibility: pytorch lightning seed
pl_seed: 42 # False or seed number, e.g., 42

log_dir: lightning_logs
log_path: ${log_dir}/${exp_name}
ckpt_path: ${log_path}/checkpoints
test_path: ${log_path}/test_${now:%Y%m%d}_${now:%H%M%S.%f}_${ckpt_type}_${data.crop_size_test}

matplotlib_backend: Agg
matplotlib_style:
  text.usetex: true
  font.family: serif
  pgf.texsystem: pdflatex
  pgf.rcfonts: false
  
hydra:
  job:
    name: test_treeAI_semseg
  launcher:
    timeout_min: 120
    gres: gpu:1
    partition: wegner
    constraint: "GPUMEM32GB|GPUMEM80GB"
    mem_gb: 64
    cpus_per_task: 8

  sweep:
    dir: ${log_path}/hydra/multirun/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}
  run:
    dir: ${log_path}/hydra/${now:%Y-%m-%d-%H-%M-%S}
